name: docker-hub-push

on:
  push:
    tags:
      - prod-*

env:
  DOCKER_REGISTRY: ekacare
  DOCKER_REPO: ${{ github.event.repository.name }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}         

      - name: Get the version and transform tag
        id: get_version
        run: |
          # Extract the version by removing 'prod-' prefix and adding 'v'
          VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/^prod-/v/')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64        
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug        
          
      - name: Docker Build
        id: docker-build
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker buildx build --platform $PLATFORMS -t $DOCKER_REGISTRY/$DOCKER_REPO:$IMAGE_TAG --push -f Dockerfile .
